import type {codeSnippet} from "./types.js"
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

// Load code snippets from JSON file (generated by npm run generate-snippets)
export const CODE_SNIPPIT_OBJECTS: codeSnippet[] = require('./codeSnippets.json');

// Raw snippets kept for regeneration purposes
export const CODE_SNIPPETS_RAW: string[] = [
  `int factorial(int n) {
    if (n <= 1) {
        return 1;
    }
    return n * factorial(n - 1);
}`,

  `void swap(int *a, int *b) {
    int temp = *a;
    *a = *b;
    *b = temp;
}`,

  `int binary_search(int arr[], int size, int target) {
    int left = 0;
    int right = size - 1;

    while (left <= right) {
        int mid = left + (right - left) / 2;
        if (arr[mid] == target) {
            return mid;
        }
        if (arr[mid] < target) {
            left = mid + 1;
        } else {
            right = mid - 1;
        }
    }
    return -1;
}`,

  `void bubble_sort(int arr[], int n) {
    for (int i = 0; i < n - 1; i++) {
        for (int j = 0; j < n - i - 1; j++) {
            if (arr[j] > arr[j + 1]) {
                int temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
            }
        }
    }
}`,

  `struct Node *reverse_list(struct Node *head) {
    struct Node *prev = NULL;
    struct Node *current = head;
    struct Node *next = NULL;

    while (current != NULL) {
        next = current->next;
        current->next = prev;
        prev = current;
        current = next;
    }
    return prev;
}`
];
